(refactor)(bash): make the job monitor more resilient
Signed-off-by: ksatchit <karthik.s@openebs.io>

diff --git a/script/utils/litmus_job_runner b/script/utils/litmus_job_runner
--- a/script/utils/litmus_job_runner
+++ b/script/utils/litmus_job_runner
@@ -28,12 +28,38 @@ jobStateCmd="kubectl get pod ${litmus_pod} --no-headers -n litmus -o custom-colu
 
 ## TODO: Consider cases where litmus pod is evicted
 
+: << EOF
 while [[ ! $(eval ${containerStateCmd}) =~ 'terminated' ]]; do
   sleep 1 
 done 
 
 while [[ $(eval ${jobStateCmd}) =~ 'Running' ]]; do
    sleep 1
+done
+EOF
+
+while true; do
+  cstate=$(eval ${containerStateCmd}); rc=$?
+  if [[ $rc -eq 0 ]]; then
+    if [[ ! $cstate =~ 'terminated' ]]; then 
+      sleep 1
+    else break;
+    fi
+  else 
+    echo "unable to get litmus container status"; exit 1
+  fi
+done
+  
+while true; do
+  jstate=$(eval ${jobStateCmd}); rc=$?
+  if [[ $rc -eq 0 ]]; then
+    if [[ $jstate =~ 'Running' ]]; then 
+      sleep 1
+    else break;
+    fi
+  else 
+    echo "unable to get litmus job status"; exit 1
+  fi
 done
 
 echo "Litmus test run Job has completed"
